### ISSUE TITLE
Can't run the toolchain

### ISSUE THREAD

**Issue by Ilir-Liburn** [jjhenkel/c2ocaml#3]
Hello,

I would like to try your tool, but I'm getting error(s). Could you be kind to check what is going on?

Thank you

```
developer@DESKTOP:~/code-vectors-artifact$ make end-to-end-redis
git submodule init
git submodule update --remote
[code-vectors] Ensuring we have lsee
docker pull jjhenkel/lsee
Using default tag: latest
latest: Pulling from jjhenkel/lsee
Digest: sha256:b034e2a9b67b1e0a7e3765e4038909fdff95834cb93123cba536bfb9effb7182
Status: Image is up to date for jjhenkel/lsee:latest
docker.io/jjhenkel/lsee:latest
[code-vectors] Ensuring that we have c2ocaml
docker pull jjhenkel/c2ocaml
Using default tag: latest
latest: Pulling from jjhenkel/c2ocaml
Digest: sha256:ef8bf7a3c551811bab056a380d6cae91453dc24edd6ec9c6991e443437cb51c4
Status: Image is up to date for jjhenkel/c2ocaml:latest
docker.io/jjhenkel/c2ocaml:latest
[code-vectors] Running end-to-end pipeline on redis...
[code-vectors] Transforming sources...
pushd /home/developer/code-vectors-artifact/c2ocaml ; make redis ; popd
~/code-vectors-artifact/c2ocaml ~/code-vectors-artifact
make[1]: Entering directory '/home/developer/code-vectors-artifact/c2ocaml'
[c2ocaml] Ensuring we have gcc7.2.0
docker pull jjhenkel/gcc7.2.0
Using default tag: latest
latest: Pulling from jjhenkel/gcc7.2.0
Digest: sha256:3b115f72180f4404aa105342cb81fcd826231a5d4f086d69917da47cf3527753
Status: Image is up to date for jjhenkel/gcc7.2.0:latest
docker.io/jjhenkel/gcc7.2.0:latest
[c2ocaml] Creating c2ocaml-gcc7.2.0 container
docker rm c2ocaml-gcc7.2.0 &> /dev/null || true
docker run --name=c2ocaml-gcc7.2.0 jjhenkel/gcc7.2.0 /entrypoint.sh
[c2ocaml] Copying GCC 7.2.0 to output volume
[c2ocaml] Ensuring we have c2ocaml
docker pull jjhenkel/c2ocaml
Using default tag: latest
latest: Pulling from jjhenkel/c2ocaml
Digest: sha256:ef8bf7a3c551811bab056a380d6cae91453dc24edd6ec9c6991e443437cb51c4
Status: Image is up to date for jjhenkel/c2ocaml:latest
docker.io/jjhenkel/c2ocaml:latest
[c2ocaml] Creating c2ocaml-build container
docker rm c2ocaml-build &> /dev/null || true
docker run --name=c2ocaml-build --volumes-from=c2ocaml-gcc7.2.0:ro -v /home/developer/code-vectors-artifact/c2ocaml/plugin:/app/Lets/Transform/plugin jjhenkel/c2ocaml
+ mv /usr/bin/cc /usr/bin/cc_
+ mv /usr/bin/gcc /usr/bin/gcc_
+ ln -s /mnt/gcc7.3.0/bin/gcc /usr/bin/cc
+ ln -s /mnt/gcc7.3.0/bin/gcc /usr/bin/gcc
+ ln -s /mnt/gcc7.3.0/bin/g++ /usr/bin/g++
Configuring...
+ echo Configuring...
+ cd ./plugin/Build
+ cmake .
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/app/Lets/Transform/plugin/Build/CMakeFiles/CMakeOutput.log".
See also "/app/Lets/Transform/plugin/Build/CMakeFiles/CMakeError.log".
make[1]: *** [Makefile:57: c2ocaml] Error 1
make[1]: Leaving directory '/home/developer/code-vectors-artifact/c2ocaml'
~/code-vectors-artifact
[code-vectors] Generating traces...
pushd /home/developer/code-vectors-artifact/lsee ; make redis ; popd
~/code-vectors-artifact/lsee ~/code-vectors-artifact
make[1]: Entering directory '/home/developer/code-vectors-artifact/lsee'
[lsee] Ensuring we have lsee
docker pull jjhenkel/lsee
Using default tag: latest
latest: Pulling from jjhenkel/lsee
Digest: sha256:b034e2a9b67b1e0a7e3765e4038909fdff95834cb93123cba536bfb9effb7182
Status: Image is up to date for jjhenkel/lsee:latest
docker.io/jjhenkel/lsee:latest
[lsee] Generating traces for redis...
[lsee] Using 8 workers...
/home/developer/code-vectors-artifact/lsee/lsee-all ../c2ocaml/artifacts/redis
find: ‘../c2ocaml/artifacts/redis’: No such file or directory
find: ‘../c2ocaml/artifacts/redis’: No such file or directory
find: ‘../c2ocaml/artifacts/redis’: No such file or directory
find: ‘../c2ocaml/artifacts/redis’: No such file or directory
[lsee] Temporary Makefile generated
time make -f ./artifacts/Makefile.temp -j$(getconf _NPROCESSORS_ONLN) all
make[2]: Entering directory '/home/developer/code-vectors-artifact/lsee'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/developer/code-vectors-artifact/lsee'

real    0m0.012s
user    0m0.007s
sys     0m0.006s
[lsee] Generated traces! Run 'NAME=redis make collect' to build a trace corpus.
make[1]: Leaving directory '/home/developer/code-vectors-artifact/lsee'
~/code-vectors-artifact
[code-vectors] Collecting traces...
pushd /home/developer/code-vectors-artifact/lsee ; NAME=redis make collect ; popd
~/code-vectors-artifact/lsee ~/code-vectors-artifact
make[1]: Entering directory '/home/developer/code-vectors-artifact/lsee'
[lsee] Creating trace corpus /home/developer/code-vectors-artifact/lsee/redis.traces.txt
cat /home/developer/code-vectors-artifact/lsee/artifacts/*.traces > "/home/developer/code-vectors-artifact/lsee/redis.traces.txt"
cat: '/home/developer/code-vectors-artifact/lsee/artifacts/*.traces': No such file or directory
make[1]: *** [Makefile:119: collect] Error 1
make[1]: Leaving directory '/home/developer/code-vectors-artifact/lsee'
~/code-vectors-artifact
[code-vectors] Completed end-to-end run on redis!
[code-vectors] Run make learn-vectors-redis to learn vectors using GloVe!
```

**Comment by jjhenkel** [comment]
Looks like this was me having my versions out-of-sync. I've updated references for `gcc` to `7.3.0`. These changes are pushed here and to the main `code-vectors-artifact` repo. After the changes I was able to do a full `end-to-end-redis` run. You should be able to pull those changes and re-run now! Let me know if that doesn't help.

**Comment by Ilir-Liburn** [comment]
Sorry for late reply, but I'm not able to get Docker running on my machine, therefore I wasn't able to test changes. Once (if) I'm able to get docker running I'll come back. In mean time, would you be kind to explain what c2ocaml tool can do, seems to be converting C to lsee. What is lsee? Is it some kind of VM working on top of OCaml? I would like to know how toolchain works to see if it is useful for me.

**Comment by jjhenkel** [comment]
No problem! (My replies may be delayed as well---leaving for a Summer internship in a few days.)

This is older work, so I'm going off memory here, but `c2ocaml` is a GCC plugin that, during compilation of a C program, takes each procedure in the target program and generates a corresponding OCaml program which, when compiled and executed, simulates a form of lightweight symbolic execution for the target procedure.

In other words, you integrate this tool with some buildable C code like `redis` or the Linux kernel, and this tool will give you a bunch of OCaml programs that can be passed to `lsee` for lighweight symbolic execution (`lsee` stands for: Lightweight Symbolic Execution Engine). `lsee` produces a bounded number of simple execution traces, and (in this paper) we used those to learn word vectors (and do some LSTM learning over traces). In general, you don't have to use the traces for learning---once you've extracted them you can do whatever you want!

One thing that people often forget when evaluating this tool is that the _target program must be buildable_. This is a big limitation. You can't give `c2ocaml` (and then `lsee`) a directory of C files---you must start with something that builds, using whatever build system (backed by GCC) and then integrate this tool into the build process. (And, primarily, that's what these repos are---the tools + integration into builds for `redis` and other example targets.)

Hope this helps give some context!

**Comment by Ilir-Liburn** [comment]
But is it possible to build executable, I mean Ocaml->executable out of C code? Or is this tool just to analyse and get better understanding of C code?

**Comment by jjhenkel** [comment]
This tool is to analyze C code (but via symbolic traces, not via some OCaml interface). It goes from C code -> OCaml (think of this as an intermediary representation) -> Executable -> (Abstracted) Symbolic Traces for the original C code. If you're looking for an OCaml framework/library for analyzing C then this isn't a good fit. If you're looking to do lighweight symbolic execution for C procedures (intra-procedural, no path feasibility checking, very basic memory model) then this may be for you!

**Comment by Ilir-Liburn** [comment]
That may be a tool I'm looking for. But I have to solve Docker issues first. Thanks, have a good time at internship.

**Comment by jjhenkel** [comment]
Understood. And thanks!

Feel free to email me if you have more questions, my email is on my website: [https://pages.cs.wisc.edu/~jjhenkel](https://pages.cs.wisc.edu/~jjhenkel). Closing this for now.

**Comment by Ilir-Liburn** [comment]
It seems I have no luck. Now I got Docker up and running, but still getting errors from toolchain

```
git submodule init
git submodule update --remote
[code-vectors] Ensuring we have lsee
docker pull jjhenkel/lsee
Using default tag: latest
latest: Pulling from jjhenkel/lsee
3e17c6eae66c: Pull complete
28befeb41e57: Pull complete
c660c38896a8: Pull complete
9454cb50c20c: Pull complete
48a70678f4c2: Pull complete
e78fb78a018f: Pull complete
fdf397ddb866: Pull complete
b14f0c219de6: Pull complete
709b1cc5d924: Pull complete
0ed1c11b8199: Pull complete
Digest: sha256:b034e2a9b67b1e0a7e3765e4038909fdff95834cb93123cba536bfb9effb7182
Status: Downloaded newer image for jjhenkel/lsee:latest
docker.io/jjhenkel/lsee:latest
[code-vectors] Ensuring that we have c2ocaml
docker pull jjhenkel/c2ocaml
Using default tag: latest
latest: Pulling from jjhenkel/c2ocaml
cd8eada9c7bb: Pull complete
fc48b86a1cde: Pull complete
6f50f97c0d1c: Pull complete
fef2d60729d5: Pull complete
Digest: sha256:ef8bf7a3c551811bab056a380d6cae91453dc24edd6ec9c6991e443437cb51c4
Status: Downloaded newer image for jjhenkel/c2ocaml:latest
docker.io/jjhenkel/c2ocaml:latest
[code-vectors] Running end-to-end pipeline on redis...
[code-vectors] Transforming sources...
pushd /home/developer/code-vectors-artifact/c2ocaml ; make redis ; popd
~/code-vectors-artifact/c2ocaml ~/code-vectors-artifact
make[1]: Entering directory '/home/developer/code-vectors-artifact/c2ocaml'
[c2ocaml] Ensuring we have gcc7.3.0
docker pull jjhenkel/gcc7.3.0
Using default tag: latest
latest: Pulling from jjhenkel/gcc7.3.0
cd8eada9c7bb: Already exists
6d1da401607e: Pull complete
55dc6093106d: Pull complete
bea109344fa0: Pull complete
2b105b184690: Pull complete
226dee06b036: Pull complete
424fa70b1976: Pull complete
Digest: sha256:2a2fa34e19bf7b5f2d27d55b50bff2c5f87e13692ebb0ed78eb9af9160e07e94
Status: Downloaded newer image for jjhenkel/gcc7.3.0:latest
docker.io/jjhenkel/gcc7.3.0:latest
[c2ocaml] Creating c2ocaml-gcc7.3.0 container
docker rm c2ocaml-gcc7.3.0 &> /dev/null || true
docker run --name=c2ocaml-gcc7.3.0 jjhenkel/gcc7.3.0 /entrypoint.sh
[c2ocaml] Copying GCC 7.3.0 to output volume
[c2ocaml] Ensuring we have c2ocaml
docker pull jjhenkel/c2ocaml
Using default tag: latest
latest: Pulling from jjhenkel/c2ocaml
Digest: sha256:ef8bf7a3c551811bab056a380d6cae91453dc24edd6ec9c6991e443437cb51c4
Status: Image is up to date for jjhenkel/c2ocaml:latest
docker.io/jjhenkel/c2ocaml:latest
[c2ocaml] Creating c2ocaml-build container
docker rm c2ocaml-build &> /dev/null || true
docker run --name=c2ocaml-build --volumes-from=c2ocaml-gcc7.3.0:ro -v /home/developer/code-vectors-artifact/c2ocaml/plugin:/app/Lets/Transform/plugin jjhenkel/c2ocaml
+ mv /usr/bin/cc /usr/bin/cc_
+ mv /usr/bin/gcc /usr/bin/gcc_
+ ln -s /mnt/gcc7.3.0/bin/gcc /usr/bin/cc
+ ln -s /mnt/gcc7.3.0/bin/gcc /usr/bin/gcc
+ ln -s /mnt/gcc7.3.0/bin/g++ /usr/bin/g++
Configuring...
+ echo Configuring...
+ cd ./plugin/Build
/app/Lets/Transform/entrypoint.sh: line 13: cd: ./plugin/Build: No such file or directory
make[1]: *** [Makefile:57: c2ocaml] Error 1
make[1]: Leaving directory '/home/developer/code-vectors-artifact/c2ocaml'
~/code-vectors-artifact
[code-vectors] Generating traces...
pushd /home/developer/code-vectors-artifact/lsee ; make redis ; popd
~/code-vectors-artifact/lsee ~/code-vectors-artifact
make[1]: Entering directory '/home/developer/code-vectors-artifact/lsee'
[lsee] Ensuring we have lsee
docker pull jjhenkel/lsee
Using default tag: latest
latest: Pulling from jjhenkel/lsee
Digest: sha256:b034e2a9b67b1e0a7e3765e4038909fdff95834cb93123cba536bfb9effb7182
Status: Image is up to date for jjhenkel/lsee:latest
docker.io/jjhenkel/lsee:latest
[lsee] Generating traces for redis...
[lsee] Using 8 workers...
/home/developer/code-vectors-artifact/lsee/lsee-all ../c2ocaml/artifacts/redis
find: ‘../c2ocaml/artifacts/redis’: No such file or directory
find: ‘../c2ocaml/artifacts/redis’: No such file or directory
find: ‘../c2ocaml/artifacts/redis’: No such file or directory
find: ‘../c2ocaml/artifacts/redis’: No such file or directory
[lsee] Temporary Makefile generated
time make -f ./artifacts/Makefile.temp -j$(getconf _NPROCESSORS_ONLN) all
make[2]: Entering directory '/home/developer/code-vectors-artifact/lsee'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/developer/code-vectors-artifact/lsee'

real    0m0.103s
user    0m0.000s
sys     0m0.078s
[lsee] Generated traces! Run 'NAME=redis make collect' to build a trace corpus.
make[1]: Leaving directory '/home/developer/code-vectors-artifact/lsee'
~/code-vectors-artifact
[code-vectors] Collecting traces...
pushd /home/developer/code-vectors-artifact/lsee ; NAME=redis make collect ; popd
~/code-vectors-artifact/lsee ~/code-vectors-artifact
make[1]: Entering directory '/home/developer/code-vectors-artifact/lsee'
[lsee] Creating trace corpus /home/developer/code-vectors-artifact/lsee/redis.traces.txt
cat /home/developer/code-vectors-artifact/lsee/artifacts/*.traces > "/home/developer/code-vectors-artifact/lsee/redis.traces.txt"
cat: '/home/developer/code-vectors-artifact/lsee/artifacts/*.traces': No such file or directory
make[1]: *** [Makefile:119: collect] Error 1
make[1]: Leaving directory '/home/developer/code-vectors-artifact/lsee'
~/code-vectors-artifact
[code-vectors] Completed end-to-end run on redis!
[code-vectors] Run make learn-vectors-redis to learn vectors using GloVe!
```

**Comment by jjhenkel** [comment]
Can you tell me what command you're using to get these logs? And can you try just doing a fresh clone (remove the `code-vectors-artifact` repository and sub-repositories and start fresh)? I'm able to run `make end-to-end-redis` on my Debian desktop from a fresh clone of the `code-vectors-artifact` repository.

**Comment by Ilir-Liburn** [comment]
I use Docker Desktop on Windows Pro + WSL1, clone of your git repository and then run make end-to-end-redis

**Comment by Ilir-Liburn** [comment]
Tomorrow I will try to switch to WSL2 because it is a VM running full Linux distro, but last time I tried that, I had to shutdown Windows, everything just exploded.

**Comment by jjhenkel** [comment]
Sounds good. I don't think I have tested this in WSL and, from personal experience, I know that mounting volumes (at least in WSL 1) was a little tricky. (And, unfortunately, there are volume mounts all over the place in this chain of tools.) If WSL2 doesn't help it's likely that your best solution would be to try and run this on a `*nix` system with a recent Docker install.

**Comment by Ilir-Liburn** [comment]
Finally, I succeeded. The trick was: V-Hyper manager configuration where paging is set to use external device. It took whole afternoon to build end-to-end-redis, but there was no error at the end. Amazing. Now I have something to play with. Thank you.

**Comment by jjhenkel** [comment]
Glad to hear it! Also, if you're just interested in the end product (traces) I have a bunch from a run on the Linux kernel [here](https://uwmadison.box.com/s/p45k1mtuylfd1t35p32rihyouzj34oaw).

**Comment by Ilir-Liburn** [comment]
Please give me some time to first understand how to use this tool. I'm also new to Docker, so I'm now looking how and where to look for traces. I found bunch of Ocaml files generated under c2ocaml/artifacts/redis directory under WSL2 (Debian), but I suspect traces are stored somewhere else by Docker?

**Comment by jjhenkel** [comment]
At some point traces are broken down per file (and I think stored in `./lsee/artifacts`). Near the end of execution they are put into one big corpus where the first word on each line is the function name (from which the traces came) and then the rest of the (space separated) words are the trace. So, if I run `make end-to-end-redis` I find a `./lsee/redis.traces.txt` file with traces in the format I described above.

**Comment by Ilir-Liburn** [comment]
Yes, I found it. It's quite big. I will look into it later... Thanks

**Comment by Ilir-Liburn** [comment]
OK, now I have questions. Inside lsee/artifacts, there are build.log and error.log files. What they are? Under c2ocaml/artifacts/redis, we have Ocaml files. How they are generated and why? How should I read redis.traces.txt? Is there any specification about lsee? What execution means in lsee? There is something executed afterwards?

**Comment by jjhenkel** [comment]
`build.log` is the result of "building" the OCaml program to simulate symbolic execution for a target C procedure. `err.log` are for errors during build/execution. The workflow here is `C -> OCaml -> Exe -> Trace`. So `c2ocaml` uses a GCC Plugin to do the `C -> OCaml` step. Then `lsee` comes in, builds all those OCaml files, and executes each of the resulting exes to get traces (so it does `OCaml -> Exe -> Trace`. The traces have "abstract tokens" in them that encode the results of our lightweight execution. There's no memory model (so pointers / indirect function calls / etc. aren't well handled) and there's no path feasibility checking. It's really meant to give simple results you pass into a learner/miner of some sort. The paper has a few more details on the abstraction used / choices made.

**Comment by Ilir-Liburn** [comment]
So I should look into Ocaml files because traces are generated there, and then I should have better understanding of lsee?

**Comment by jjhenkel** [comment]
You can look at those (auto-generated) files to see the structure. The "execution" code is in the `lsee` repository itself. This is the "entrypoint" [https://github.com/jjhenkel/lsee/blob/master/lib/driver.ml](https://github.com/jjhenkel/lsee/blob/master/lib/driver.ml).

**Comment by jjhenkel** [comment]
Here's an example of what you'd see in those `OCaml` files. Note how there's some debugging meta data in the comments. The idea here is that this OCaml object is encoding the Control Flow Graph of `dictUnlick` which is some C procedure in `redis`. With support from the code in the `lsee` repository, you can compile something like the below into an exe that, when run, will go ahead and "walk" paths through the Control Flow Graph (encoded below) and produce traces.

```ocaml
let main = 
(*-------------------------------------------------------- 
  // working_directory: /target/redis/src
  // source_file_name: dict.c
  // base_name: dict.c
  // name: dictUnlink
  // fid: 45
  ---------------------------------------------------------*)

  let _typeSELF = GccType.pointer(GccType.self)
  in let type0x7f51d0b0d738 = 
    GccType.record("dictEntry", [|
        (* var decls *)
      |], [|
        (* field decls *)
      |], [|
        (* type decls *)
      |], [|
        (* const decls *)
      |])
  in let type0x7f51d0b10d20 = 
    GccType.pointer(type0x7f51d0b0d738)
  in let type0x7f51d0b12930 = 
    GccType.record("dict", [|
        (* var decls *)
      |], [|
        (* field decls *)
      |], [|
        (* type decls *)
      |], [|
        (* const decls *)
      |])
  in let type0x7f51d0b12b28 = 
    GccType.pointer(type0x7f51d0b12930)
  in let type0x7f51d18c6150 = 
    GccType.void
  in let type0x7f51d18c61f8 = 
    GccType.pointer(type0x7f51d18c6150)
  in let type0x7f51d18be5e8 = 
    GccType.integer(true, 32, 32, Z.of_string "-2147483648", Z.of_string "2147483647")
  in let expr0x7f51d0bc0080 = 
    Expr.parameter_decl(type0x7f51d0b12b28, "ht", type0x7f51d0b12b28)
  in let expr0x7f51d0c99090 = 
    Expr.ssa("ht_2(D)", 2, expr0x7f51d0bc0080)
  in let expr0x7f51d0bc0100 = 
    Expr.parameter_decl(type0x7f51d18c61f8, "key", type0x7f51d18c61f8)
  in let expr0x7f51d0c990d8 = 
    Expr.ssa("key_3(D)", 3, expr0x7f51d0bc0100)
  in let expr0x7f51d18c3090 = 
    Expr.s_int_cst(type0x7f51d18be5e8, Z.of_string "1")
  in let expr0x7f51d0c99168 = 
    Expr.ssa("_5", 5, Expr.nothing(type0x7f51d0b10d20))
  in let call0x7f51d0b3cb48 = Expr.call(
    type0x7f51d0b10d20,
    "dictGenericDelete", [|
      (Expr.parameter("d", 0, expr0x7f51d0c99090));
      (Expr.parameter("key", 1, expr0x7f51d0c990d8));
      (Expr.parameter("nofree", 2, expr0x7f51d18c3090));
  |])
  in let block_0 = 
    let step_0_0 = Action.start 
    in Block.block (
      0,
      [| step_0_0 |],
      [||],
      [| "<ENTRY>" |]
    )
  in let block_2 = 
    let step_2_1 = 
      Action.call(call0x7f51d0b3cb48)
    in let step_2_2 = 
      Action.assign(expr0x7f51d0c99168, call0x7f51d0b3cb48)
    in let step_2_3 = 
      Action.return(expr0x7f51d0c99168)
    in Block.block(
      2,
      [|
        step_2_1;
        step_2_2;
        step_2_3;
      |],
      [|
        ("dictGenericDelete", 1);
      |],
      [|
        "# .MEM_4 = VDEF <.MEM_1(D)>\n_5 = dictGenericDelete (ht_2(D), key_3(D), 1);";
        "<CAPTURES RETURN>";
        "# VUSE <.MEM_4>\nreturn _5;";
      |]
    )
  in let block_1 = 
    let step_0_4 = Action.finish 
    in Block.block (
      1,
      [| step_0_4 |],
      [||],
      [| "<EXIT>" |]
    )
  in let cfg = Cfg.cfg (
    3,
    Z.of_string "1",
    [|
      Cfg.vert ("[0]", block_0, [|
          Cfg.edge (2, "[2]", block_2, Z.of_string "0", Z.of_string "0");
        |]
      );
      Cfg.vert ("[1]", block_1, [|
        |]
      );
      Cfg.vert ("[2]", block_2, [|
          Cfg.edge (1, "[1]", block_1, Z.of_string "0", Z.of_string "0");
        |]
      );
    |]
  )
  in Proc.proc(
   "dictUnlink",
    45,
   "/target/redis/src",
   "dict.c",
   "dict.c",
    cfg
  )
in Driver.execute main;;
```

**Comment by Ilir-Liburn** [comment]
OK, now I have a starting point and I will come back here if there is any more question. Thanks.
You mentioned some paper about lsee, where is it located?

**Comment by jjhenkel** [comment]
[Here it is on the ACM website](https://dl.acm.org/doi/abs/10.1145/3236024.3236085) (note: this paper is about the whole project, with some details about the execution, but really the execution was a means-to-an-end for doing some Machine Learning). You can also find a copy of the paper [on my homepage](https://pages.cs.wisc.edu/~jjhenkel/).

**Comment by Ilir-Liburn** [comment]
Actually, I have one question right now. What would be the easiest way to compile some C code now? Let's say, I will prepare some Hello World example where I just call one function writing Hello message to the console. How can I build this example without affecting code-vectors-artifact?

**Comment by jjhenkel** [comment]
Best way to "experiment" with C code is to throw it into a repository. Look at these locations to see how I do it for one experiment I ran with a bunch of C files in a repository:

You specify your "target" in a file like this:
https://github.com/jjhenkel/c2ocaml/blob/master/corpus/changed-error-codes.env

Add the necessary plumbing to get c2ocaml to run on that target:
https://github.com/jjhenkel/c2ocaml/blob/45846edf17079327c65c41aba19222b1f1e6e70e/Makefile#L164

Same thing for lsee:
https://github.com/jjhenkel/code-vectors-artifact/blob/7b80cc7e07df862dad380065f06acba3129f8b26/Makefile#L103

And, lastly, a target in the top-level repo to drive the whole workflow:
https://github.com/jjhenkel/lsee/blob/3255b4f61197e0fd816ac2e9ac1c97dbb72726a6/Makefile#L93

**Comment by Ilir-Liburn** [comment]
OK, I will take a look at those. Thanks

**Comment by Ilir-Liburn** [comment]
I need more help, this time about Git. I made a fork of your repository, but when I clone my repository, only main files are present, for example lsee and c2ocaml directories are empty. Now, documentation is saying that I need to add upstream first (to your repository), and then run git fetch upstream to get rest of files. But that doesn't happen, do you know what I'm doing wrong? Here is output of git remote -v

```
origin  https://github.com/Ilir-Liburn/code-vectors-artifact.git (fetch)
origin  https://github.com/Ilir-Liburn/code-vectors-artifact.git (push)
upstream        https://github.com/jjhenkel/code-vectors-artifact.git (fetch)
upstream        https://github.com/jjhenkel/code-vectors-artifact.git (push)
```

EDIT: Odd, I can get all files while cloning using Git Desktop

**Comment by jjhenkel** [comment]
Have you used git submodules before? There are 3 submodules in that main git repo. I'm guessing Git Desktop is taking care of this behind the scenes for you.

When you pull a repo with submodules you'll also need to do: `git submodule update --init --recursive` (for the first time). To update the submodules later something like: `git submodule update --recursive --remote`.

**Comment by Ilir-Liburn** [comment]
No, I haven't used submodules before. In fact, I haven't used git at all. Why is that not documented among tutorials bellow, I wonder. I followed this tutorials:

https://help.github.com/en/github/getting-started-with-github/fork-a-repo
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

simply explained on this blog

https://ardalis.com/syncing-a-fork-of-a-github-repository-with-upstream/

**Comment by jjhenkel** [comment]
Ah, I see. Unfortunately, git is a wildly complex piece of software and submodules are just one of many advanced features. It will take some time to get acclimated to git, that's for sure!

**Comment by Ilir-Liburn** [comment]
Sure it will take time. For example, I cloned my repo, then I switched to new branch. Here I expected to see submodules using my repo after git submodule update --init --recursive command, but git remote -v command is still showing your repo. Now I have to use git remote add \<somename\> \<myrepo\> in order to use git push \<somename\> \<branch\> for each submodule. Or is there a better way?

**Comment by jjhenkel** [comment]
It's going to be hard for me to debug this on my end because I'm not sure what you have setup / what state your environment is in. I'd advise getting comfortable with git first before forking/messing with the structure of things. You can always just clone the original repository (and get the sub modules) and then play around with things on your local disk (without worrying about trying to sync things up with git). That might be easier if you're new to git.
